### PR TITLE
Make `create key` conserve old keys by default

### PR DESCRIPTION
**Pull request by simenheg**
Make the `create key` command conserve existing client keys by default. An `--overwrite` option is added to support the previous behavior of overwriting existing keys.

### CODE REVIEW

**Comment by fredriv** [comment]
If you have 5 keys already, should we (offer to?) delete the oldest one, instead of requiring the user to overwrite all keys?

Alternatively, offer a mechanism to delete a specific key?

**Review by fredriv — APPROVED** [review]
The changes look ok, but see the question about overwriting all keys vs deleting the oldest key.

**Comment by simenheg** [comment]
> If you have 5 keys already, should we (offer to?) delete the oldest one, instead of requiring the user to overwrite all keys?
> 
> Alternatively, offer a mechanism to delete a specific key?

Jepp, tenker at begge disse tingene er gode forbedringer. Trengte å få inn denne funksjonen litt kvikt, så tenker at de kan få ønskelistestatus. I mellomtiden går det også an å slette nøkler manuelt i Samarbeidsportalen hvis det blir fullt, men håper egentlig å få inn ordentlig selvbetjent rotering i `okdata-cli` før den tid! :D

**Review by gitanjalis — COMMENTED** [review]
💯

**Pull request merged**
